#!/bin/bash
IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
IP=${IP#addr:}

echo "standing up docs"
#standup the docs
#install hugo
mkdir /opt
sudo mkdir /opt/hugo
wget -P /tmp/ https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz
sudo tar -xvf /tmp/hugo_0.26_Linux-64bit.tar.gz -C /opt/hugo

git submodule update --init
git submodule sync
cd docsrc 
/opt/hugo/hugo serve --bind 0.0.0.0  --appendPort  --baseUrl "http://${IP}/" &
